export const statusOptions = [
  { value: "นิสิตปัจจุบัน", label: "นิสิตปัจจุบัน" },
  { value: "ศิษย์เก่า", label: "ศิษย์เก่า" },
];

export const typeOptions = [
  { value: "important", label: "เอกสารสำคัญ" },
  { value: "request", label: "เอกสารคำร้อง" },
];

export const importantDocOptions = [
  { value: "CR23", label: "จท23/CR23 (หนังสือรับรองความเป็นนิสิต)" },
  { value: "CR24", label: "จท24/CR24 (หนังสือรับรองความประพฤติ)" },
  { value: "CR25", label: "จท25/CR25 (ใบประมวลการศึกษา)" },
];

export const requestDocOptions = [
  { value: "CR41", label: "จท41/CR41 (คำร้องทั่วไป)" },
  { value: "CR45", label: "จท45/CR45 (คำร้องขอรับเงินคืน)" },
  { value: "CR50", label: "จท50/CR50 (คำร้องขอทำบัตรประจำตัวนิสิต)" },
];

export const semesterOptions = [
  { value: "ต้น", label: "ต้น / 1st Semester" },
  { value: "ปลาย", label: "ปลาย / 2nd Semester" },
  { value: "ฤดูร้อน", label: "ฤดูร้อน / Summer Session" },
  { value: "ภาคที่ 1", label: "ภาคที่ 1 / 1st Trimester" },
  { value: "ภาคที่ 2", label: "ภาคที่ 2 / 2nd Trimester" },
  { value: "ภาคที่ 3", label: "ภาคที่ 3 / 3rd Trimester" },
];

export const facultyOptions = [
  {
    value: "1",
    label: "สถาบันภาษาไทยสิรินธร THE SIRINDHORN THAI LANGUAGE INSTITUTE",
  },
  { value: "2", label: "ศูนย์การศึกษาทั่วไป OFFICE OF ACADEMIC AFFAIRS" },
  { value: "20", label: "บัณฑิตวิทยาลัย GRADUATE SCHOOL" },
  { value: "21", label: "คณะวิศวกรรมศาสตร์ FACULTY OF ENGINEERING" },
  { value: "22", label: "คณะอักษรศาสตร์ FACULTY OF ARTS" },
  { value: "23", label: "คณะวิทยาศาสตร์ FACULTY OF SCIENCE" },
  { value: "24", label: "คณะรัฐศาสตร์ FACULTY OF POLITICAL SCIENCE" },
  { value: "25", label: "คณะสถาปัตยกรรมศาสตร์ FACULTY OF ARCHITECTURE" },
  {
    value: "26",
    label: "คณะพาณิชยศาสตร์และการบัญชี FACULTY OF COMMERCE AND ACCOUNTANCY",
  },
  { value: "27", label: "คณะครุศาสตร์ FACULTY OF EDUCATION" },
  { value: "28", label: "คณะนิเทศศาสตร์ FACULTY OF COMMUNICATION ARTS" },
  { value: "29", label: "คณะเศรษฐศาสตร์ FACULTY OF ECONOMICS" },
  { value: "30", label: "คณะแพทยศาสตร์ FACULTY OF MEDICINE" },
  { value: "31", label: "คณะสัตวแพทยศาสตร์ FACULTY OF VETERINARY SCIENCE" },
  { value: "32", label: "คณะทันตแพทยศาสตร์ FACULTY OF DENTISTRY" },
  { value: "33", label: "คณะเภสัชศาสตร์ FACULTY OF PHARMACEUTICAL SCIENCES" },
  { value: "34", label: "คณะนิติศาสตร์ FACULTY OF LAW" },
  { value: "35", label: "คณะศิลปกรรมศาสตร์ FACULTY OF FINE AND APPLIED ARTS" },
  { value: "36", label: "คณะพยาบาลศาสตร์ FACULTY OF NURSING" },
  { value: "37", label: "คณะสหเวชศาสตร์ FACULTY OF ALLIED HEALTH SCIENCES" },
  { value: "38", label: "คณะจิตวิทยา FACULTY OF PSYCHOLOGY" },
  { value: "39", label: "คณะวิทยาศาสตร์การกีฬา FACULTY OF SPORTS SCIENCE" },
  {
    value: "40",
    label: "สำนักวิชาทรัพยากรการเกษตร SCHOOL OF AGRICULTURAL RESOURCES",
  },
  { value: "51", label: "วิทยาลัยประชากรศาสตร์ COLLEGE OF POPULATION STUDIES" },
  {
    value: "53",
    label: "วิทยาลัยวิทยาศาสตร์สาธารณสุข COLLEGE OF PUBLIC HEALTH SCIENCES",
  },
  { value: "55", label: "สถาบันภาษา LANGUAGE INSTITUTE" },
  {
    value: "56",
    label: "สถาบันนวัตกรรมบูรณาการ SCHOOL OF INTEGRATED INNOVATION",
  },
  {
    value: "58",
    label:
      "สถาบันบัณฑิตบริหารธุรกิจ ศศินทร์ฯ SASIN GRADUATE INSTITUTE OF BUSINESS ADMINISTION",
  },
  {
    value: "63",
    label:
      "วิทยาลัยปิโตรเลียมและปิโตรเคมี THE PETROLEUM AND PETROCHEMICAL COLLEGE",
  },
  { value: "92", label: "วิทยาลัยพยาบาลตำรวจ POLICE NURSING COLLEGE" },
  { value: "99", label: "มหาวิทยาลัยอื่น OTHER UNIVERSITY" },
];

export const provinceOptions = [
  { value: "กรุงเทพมหานคร", label: "กรุงเทพมหานคร" },
  { value: "อำนาจเจริญ", label: "อำนาจเจริญ" },
  { value: "อ่างทอง", label: "อ่างทอง" },
  { value: "บึงกาฬ", label: "บึงกาฬ" },
  { value: "บุรีรัมย์", label: "บุรีรัมย์" },
  { value: "ฉะเชิงเทรา", label: "ฉะเชิงเทรา" },
  { value: "ชัยนาท", label: "ชัยนาท" },
  { value: "ชัยภูมิ", label: "ชัยภูมิ" },
  { value: "จันทบุรี", label: "จันทบุรี" },
  { value: "เชียงใหม่", label: "เชียงใหม่" },
  { value: "เชียงราย", label: "เชียงราย" },
  { value: "ชลบุรี", label: "ชลบุรี" },
  { value: "ชุมพร", label: "ชุมพร" },
  { value: "กาฬสินธุ์", label: "กาฬสินธุ์" },
  { value: "กำแพงเพชร", label: "กำแพงเพชร" },
  { value: "กาญจนบุรี", label: "กาญจนบุรี" },
  { value: "ขอนแก่น", label: "ขอนแก่น" },
  { value: "กระบี่", label: "กระบี่" },
  { value: "ลำปาง", label: "ลำปาง" },
  { value: "ลำพูน", label: "ลำพูน" },
  { value: "เลย", label: "เลย" },
  { value: "ลพบุรี", label: "ลพบุรี" },
  { value: "แม่ฮ่องสอน", label: "แม่ฮ่องสอน" },
  { value: "มหาสารคาม", label: "มหาสารคาม" },
  { value: "มุกดาหาร", label: "มุกดาหาร" },
  { value: "นครนายก", label: "นครนายก" },
  { value: "นครปฐม", label: "นครปฐม" },
  { value: "นครพนม", label: "นครพนม" },
  { value: "นครราชสีมา", label: "นครราชสีมา" },
  { value: "นครสวรรค์", label: "นครสวรรค์" },
  { value: "นครศรีธรรมราช", label: "นครศรีธรรมราช" },
  { value: "น่าน", label: "น่าน" },
  { value: "นราธิวาส", label: "นราธิวาส" },
  { value: "หนองบัวลำภู", label: "หนองบัวลำภู" },
  { value: "หนองคาย", label: "หนองคาย" },
  { value: "นนทบุรี", label: "นนทบุรี" },
  { value: "ปทุมธานี", label: "ปทุมธานี" },
  { value: "ปัตตานี", label: "ปัตตานี" },
  { value: "พังงา", label: "พังงา" },
  { value: "พัทลุง", label: "พัทลุง" },
  { value: "พะเยา", label: "พะเยา" },
  { value: "เพชรบูรณ์", label: "เพชรบูรณ์" },
  { value: "เพชรบุรี", label: "เพชรบุรี" },
  { value: "พิจิตร", label: "พิจิตร" },
  { value: "พิษณุโลก", label: "พิษณุโลก" },
  { value: "พระนครศรีอยุธยา", label: "พระนครศรีอยุธยา" },
  { value: "แพร่", label: "แพร่" },
  { value: "ภูเก็ต", label: "ภูเก็ต" },
  { value: "ปราจีนบุรี", label: "ปราจีนบุรี" },
  { value: "ประจวบคีรีขันธ์", label: "ประจวบคีรีขันธ์" },
  { value: "ระนอง", label: "ระนอง" },
  { value: "ราชบุรี", label: "ราชบุรี" },
  { value: "ระยอง", label: "ระยอง" },
  { value: "ร้อยเอ็ด", label: "ร้อยเอ็ด" },
  { value: "สระแก้ว", label: "สระแก้ว" },
  { value: "สกลนคร", label: "สกลนคร" },
  { value: "สมุทรปราการ", label: "สมุทรปราการ" },
  { value: "สมุทรสาคร", label: "สมุทรสาคร" },
  { value: "สมุทรสงคราม", label: "สมุทรสงคราม" },
  { value: "สระบุรี", label: "สระบุรี" },
  { value: "สตูล", label: "สตูล" },
  { value: "สิงห์บุรี", label: "สิงห์บุรี" },
  { value: "ศรีสะเกษ", label: "ศรีสะเกษ" },
  { value: "สงขลา", label: "สงขลา" },
  { value: "สุโขทัย", label: "สุโขทัย" },
  { value: "สุพรรณบุรี", label: "สุพรรณบุรี" },
  { value: "สุราษฎร์ธานี", label: "สุราษฎร์ธานี" },
  { value: "สุรินทร์", label: "สุรินทร์" },
  { value: "ตาก", label: "ตาก" },
  { value: "ตรัง", label: "ตรัง" },
  { value: "ตราด", label: "ตราด" },
  { value: "อุบลราชธานี", label: "อุบลราชธานี" },
  { value: "อุดรธานี", label: "อุดรธานี" },
  { value: "อุทัยธานี", label: "อุทัยธานี" },
  { value: "อุตรดิตถ์", label: "อุตรดิตถ์" },
  { value: "ยะลา", label: "ยะลา" },
  { value: "ยโสธร", label: "ยโสธร" },
];

export const documentMap: Record<string, { name: string }> = {
  CR23: { name: "จท23 (หนังสือรับรองความเป็นนิสิต)" },
  CR24: { name: "จท24 (หนังสือรับรองความประพฤติ)" },
  CR25: { name: "จท25 (ใบประมวลผลการศึกษา)" },
  CR26: { name: "จท26 (หนังสือรับรองคุณวุฒิ)" },
  CR41: { name: "จท41 (คำร้องทั่วไป)" },
  CR44: { name: "จท44 (คำร้องขอลาป่วย)" },
  CR45: { name: "จท45 (คำร้องขอรับเงินคืน)" },
  CR50: { name: "จท50 (คำร้องขอทำบัตรประจำตัวนิสิต)" },
};
